# Site settings
title: Social Graphs
email: dpodoroghin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  assignment for the course
baseurl: "https://dianap19d.github.io/SocialDataTemplateWebsite/" # the subpath of your site, e.g. /blog
url: "https://dianap19d.github.io/SocialDataTemplateWebsite/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

